services:
  booking-transaction:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mongodb

  mongodb:
    image: 'mongo:7.0.0'
    environment:
      - 'MONGO_INITDB_DATABASE=transaction_db'
    ports:
      - '27017:27017'